# Generated by Django 5.2.7 on 2025-10-26 14:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 4),
                            ("quote", 5),
                            ("embed", 6),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "The heading text", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Heading 2"),
                                        ("h3", "Heading 3"),
                                        ("h4", "Heading 4"),
                                    ],
                                    "help_text": "Select the appropriate heading level for document hierarchy",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.RichTextBlock", (), {}),
                            4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            5: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            6: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Page",
                "verbose_name_plural": "Content Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
