# Generated by Django 5.2.7 on 2025-10-26 14:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("rich_text", 3),
                    ("image", 4),
                    ("quote", 5),
                    ("embed", 6),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "The heading text", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                            ],
                            "help_text": "Select the appropriate heading level for document hierarchy",
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    6: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                },
            ),
        ),
    ]
