# Generated by Django 5.2.7 on 2025-10-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocaleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish / Español"),
                            ("fr", "French / Français"),
                            ("de", "German / Deutsch"),
                            ("pt", "Portuguese / Português"),
                            ("it", "Italian / Italiano"),
                            ("nl", "Dutch / Nederlands"),
                            ("da", "Danish / Dansk"),
                            ("sv", "Swedish / Svenska"),
                            ("no", "Norwegian / Norsk"),
                            ("fi", "Finnish / Suomi"),
                            ("is", "Icelandic / Íslenska"),
                            ("ru", "Russian / Русский"),
                            ("ja", "Japanese / 日本語"),
                            ("zh-hans", "Chinese Simplified / 简体中文"),
                            ("zh-hant", "Chinese Traditional / 繁體中文"),
                            ("ko", "Korean / 한국어"),
                            ("ar", "Arabic / العربية"),
                            ("sw", "Swahili / Kiswahili"),
                        ],
                        default="en",
                        help_text="The default language for this site",
                        max_length=10,
                    ),
                ),
                (
                    "available_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Select the languages available on this site. Must include the default language.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Locale Settings",
            },
        ),
    ]
