# Generated by Django 5.2.7 on 2025-10-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localesettings",
            name="default_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish / Español"),
                    ("fr", "French / Français"),
                    ("de", "German / Deutsch"),
                    ("pt", "Portuguese / Português"),
                    ("it", "Italian / Italiano"),
                    ("nl", "Dutch / Nederlands"),
                    ("da", "Danish / Dansk"),
                    ("sv", "Swedish / Svenska"),
                    ("nb", "Norwegian Bokmål / Norsk bokmål"),
                    ("fi", "Finnish / Suomi"),
                    ("is", "Icelandic / Íslenska"),
                    ("ru", "Russian / Русский"),
                    ("ja", "Japanese / 日本語"),
                    ("zh-hans", "Chinese Simplified / 简体中文"),
                    ("zh-hant", "Chinese Traditional / 繁體中文"),
                    ("ko", "Korean / 한국어"),
                    ("ar", "Arabic / العربية"),
                    ("sw", "Swahili / Kiswahili"),
                ],
                default="en",
                help_text="The default language for this site",
                max_length=10,
            ),
        ),
    ]
