# Generated by Django 5.2.7 on 2025-10-09 14:13

from django.db import migrations, models


def convert_text_to_json(apps, schema_editor):
    """
    Convert comma-separated language codes to JSON array.
    """
    LocaleSettings = apps.get_model("locales", "LocaleSettings")
    for settings in LocaleSettings.objects.all():
        if isinstance(settings.available_languages, str):
            # Convert "en,es,fr" to ["en", "es", "fr"]
            codes = [
                code.strip()
                for code in settings.available_languages.split(",")
                if code.strip()
            ]
            settings.available_languages = codes
            settings.save()


def convert_json_to_text(apps, schema_editor):
    """
    Reverse migration: convert JSON array back to comma-separated string.
    """
    LocaleSettings = apps.get_model("locales", "LocaleSettings")
    for settings in LocaleSettings.objects.all():
        if isinstance(settings.available_languages, list):
            # Convert ["en", "es", "fr"] to "en,es,fr"
            settings.available_languages = ",".join(settings.available_languages)
            settings.save()


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localesettings",
            name="available_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select the languages available on this site. Must include the default language.",
            ),
        ),
        migrations.RunPython(convert_text_to_json, convert_json_to_text),
    ]
