# Generated by Django 5.2.7 on 2025-11-03 20:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationmenusetting",
            name="menu_items",
            field=wagtail.fields.StreamField(
                [("page_link", 3), ("external_link", 7), ("dropdown", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override the page title (leave blank to use page's own title)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional anchor (e.g., 'section-name' for #section-name)",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("custom_title", 1), ("anchor", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Full URL including http:// or https://",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Link text to display in menu",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional anchor (e.g., 'section' for #section)",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 4), ("title", 5), ("anchor", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Dropdown menu label",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("page_link", 3), ("external_link", 7)]],
                        {
                            "help_text": "Links to display in dropdown menu",
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("items", 9)]],
                        {},
                    ),
                },
                help_text="Configure the main navigation menu for your site.",
            ),
        ),
    ]
